### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by peterdesmet** [ranges-network/ranges-network.github.io#2]
## Todo

- [x] Add pages/about.md
- [x] Add pages/awards.md
- [x] Add pages/privacy.md
- [x] Don't forget to add a `permalink` in the metadata for those pages
- [x] Add team members to _data/team.yml (currently dummy data)
- [x] Add participants to _data/participants.yml (currently dummy data)
- [x] Review if `resources` is a good dropdown menu name
- [x] Review if footer looks fine (I made some editorial decisions)
- [x] Add socials (optional)
- [x] Use ending slashes in navigation.yml (`/about/` not `/about`)
- [x] Don't use carriage returns in paragraphs, put all text on one line
- [x] Use an empty line after headings and paragraphs
- [x] None of the files at `assets/images/favicons` are used (only the root `favicon.ico`), maybe this can be removed?
- [x] Use a CC-BY license and indicate this in footer. This is now done, but wanted to inform you of this

## Background images

I noticed the image metadata was stored in `_data/images.yml` and linked somehow from the page metadata. I'm not sure this will work. I suggest to keep it simple and add background images per page.

- [x] Remove `_data/images.yml`
- [x] If you don't want to link remote images, save them in `assets/backgrounds/`
- [x] Add images to pages cf. https://peterdesmet.com/petridish/docs/configuration/#pages

```
background:
  img: https://images.unsplash.com/photo-1507477338202-487281e6c27e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTkwfHxiaXJkc3xlbnwwfDB8MHx8&auto=format&fit=crop&crop=top&w=1200&h=600&q=80
  by: Mathew Schwartz
  href: https://unsplash.com/photos/5iFZBM7qgWc
```

## Metadata removals

I removed the following elements from page metadata, since they are not used afaik

- [x] `lang`
- [x] `lang-ref`
- [x] `height`
- [x] `imageLicense`

**Comment by dbloom** [comment]
Many thanks for this guidance.

Managed to accomplish them all.

re: favicons - added txt file describing rationale for keeping those for now.

**Comment by peterdesmet** [comment]
Tip: I would rename those text files in subdirectories to README.md, then you immediately see the rationale when browsing to that directory on GitHub.
