### ISSUE TITLE
Todo #2

### ISSUE THREAD

**Issue by dbloom** [ranges-network/ranges-network.github.io#7]
## Todo

- [ ] Add background to Core Team page
- [ ] Mention "mammals" earlier on the Awards and NewsAnnouncement pages
- [ ] Include metadata standards for Awards
- [x] Build Awards form
- [x] Add form link to Awards page
- [ ] Update Goals text in 'home.md'
- [ ] Add news.md to Navigation
- [ ] News post for 1st awards
- [ ] News post for AHM meeting in UT
- [x] Move to ranges-network.org
- [ ] ...

## Phase 2

- [ ] Update about to include research uses OR create new page
- [ ] Create Partner page OR add partners to 'particpants.md'
- [ ] Add Google Analytics?
- [ ] ...

**Comment by peterdesmet** [comment]
I made a mistake in suggesting that the `text.txt` should become README.md, as that means Jekyll will think they are content that needs to be rendered. See e.g.: https://ranges-network.github.io/assets/favicons/

Solutions:

1. (preferred) Move all instructions to the main README.md, don't have separate READMEs
2. Keep the README.md, but exclude their path in `_config`. E.g. by adding `assets/favicons/README.md` to build settings (just like you exclude LICENSE and the root README.md):

https://github.com/ranges-network/ranges-network.github.io/blob/5eca875ce83499861e4abf009f23b1b34a5e2313/_config.yml#L32-L36

3. Use `README.txt` files

**Comment by dbloom** [comment]
Noted and updated. I've added the two READMEs.

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - assets/favicons/README.md
  - _posts/README.md

I have to learn how you created that blob link. Although I'm not sure I can do it in the GH U/I.

**Comment by peterdesmet** [comment]
Blob link? The code snippet?

**Comment by dbloom** [comment]
This link https://github.com/ranges-network/ranges-network.github.io/blob/5eca875ce83499861e4abf009f23b1b34a5e2313/_config.yml#L32-L36

Looks like blob link. But I'm still newb.

**Comment by peterdesmet** [comment]
If you want to reference code in an issue:

1. In your browser, go to the file in your repository
2. Go to the line in the code you want to reference
3. Select the line number
4. Hold shift and click a further line number to select a block
5. Click the `...`
6. Click `Copy permalink`
7. Paste the link in the issue (you can recognize it with the `#L32-L36` at the end)
8. GitHub will display the link as a code snippet

<img width="889" alt="Screenshot 2023-11-03 at 10 45 31" src="https://github.com/ranges-network/ranges-network.github.io/assets/600993/d294eac1-b1b9-4ee1-a3df-874a75fc6d0f">
